title: Gregor Schmidt
author:
  name: Gregor Schmidt
  email: schmidt@nach-vorne.eu
baseurl: ""
url: "http://www.nach-vorne.eu"

permalink: ":slug"

markdown: kramdown
exclude:
  - README.md

collections:
  portfolio:
    output: true


defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: "/:year/:month/:day/:title/"
